version: "3.7"

services:

  redis:
    image: redis:latest
    container_name: redis_articles
    hostname: redis_articles
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", $REDIS_PASSWORD]
    env_file:
      .env
    volumes:
      - ./redis-data:/data

  nginx:
    image: nginx:latest
    container_name: nginx-server
    network_mode: "host" # Нужно, чтобы докер смог увидеть приложение (если приложение fastapi, например, не в докер-контейнере)
    depends_on:
      - redis
    restart: always # при падении будет стараться подняться
    ports:
      - "80:80"
    expose:
    - 80
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  redis-data:
